# Generated by Django 5.2.7 on 2025-10-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_user_activation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
